### PR TITLE
First pass: Updates to include local fonts, tailwind and a few other …

### PR DESCRIPTION
**Pull request by kemiljk**
Work in Progress

* Adds in Tailwind CSS
* Uses local variable font
* Utilises some more components for SVG assets

### CODE REVIEW

**Comment by kemiljk** [comment]
Todo: 
- [x] Fix span text colour for author on blog detail page
image

- [x] Fix back arrow container on dark to have border
image

- [x] Create icon for blog site logo and make logo into proper logotype

- [x] Swap local font to [Manrope](https://www.fontshare.com/fonts/manrope)

- [x] Fix tracking on h2 and h3 elements

- [x] Add 2 suggested posts below each article using the random sorting

**Comment by kemiljk** [comment]
Okay @tonyspiro, this update includes the following:

* Replaces font with a nicer variable sans serif (Generator)
* Adds 2 suggested posts after the main post (using `.sort(‘random’)` and `$ne: params?.slug`)
* Fixes up the Author page interface to match the main blog page
* Adds sticky header on scroll
* Includes *some* typescript files… WIP
* Tweaks a couple of things like extracting Cosmic fetches from the main body, but again, WIP (plan is to extract these to a lib file like I’ve done on my personal site and create ts interfaces for each.

**Comment by kemiljk** [comment]
@tonyspiro it's ready for you!

**Review by tonyspiro — APPROVED** [review]
LGTM!

**Pull request merged**
